services:
  web:
    image: wynneve/bitrix-web:latest
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: bitrix
    volumes:
      - db_data:/var/lib/mysql
      - ./db/bitrix.sql:/docker-entrypoint-initdb.d/bitrix.sql

volumes:
  db_data:
    driver: local